# Generated by Django 4.1.1 on 2022-10-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
