# Generated by Django 4.1.1 on 2023-12-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0004_token_bearish_token_bullish_token_codrepo_perc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='coin_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='cryptocompare_assetlaunchdate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='cryptocompare_assetwebsiteurl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='cryptocompare_imageurl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
