# Generated by Django 4.1.1 on 2023-12-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0005_alter_token_coin_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_creation', models.IntegerField(default=1313643968000, null=True)),
                ('favourites', models.IntegerField(default=1000, null=True)),
                ('followers', models.IntegerField(default=844049, null=True)),
                ('following', models.IntegerField(default=165, null=True)),
                ('lists', models.IntegerField(default=6631, null=True)),
                ('points', models.IntegerField(default=91055, null=True)),
                ('statuses', models.IntegerField(default=2031, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_module.token')),
            ],
        ),
        migrations.CreateModel(
            name='TechIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ema10', models.FloatField(default=21419.650556424, null=True)),
                ('ema50', models.FloatField(default=23477.3946873044, null=True)),
                ('ema_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bearish', max_length=10, null=True)),
                ('macd_line', models.FloatField(default=-301.3443464701, null=True)),
                ('macd_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bullish', max_length=10, null=True)),
                ('macd_signal', models.FloatField(default=-864.379150169, null=True)),
                ('mfi14', models.FloatField(default=76.7455530806, null=True)),
                ('mfi14_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bullish', max_length=10, null=True)),
                ('mom10', models.FloatField(default=1817.74, null=True)),
                ('mom10_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bullish', max_length=10, null=True)),
                ('rsi10', models.FloatField(default=69.1125657987, null=True)),
                ('rsi10_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='neutral', max_length=10, null=True)),
                ('rsi50', models.FloatField(default=43.2777984936, null=True)),
                ('rsi50_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='neutral', max_length=10, null=True)),
                ('sma10', models.FloatField(default=20957.507, null=True)),
                ('sma50', models.FloatField(default=23114.7386, null=True)),
                ('sma_sentiment', models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bearish', max_length=10, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_module.token')),
            ],
        ),
        migrations.CreateModel(
            name='RedditData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_users', models.IntegerField(default=11157, null=True)),
                ('comments_per_day', models.FloatField(default=3368.42, null=True)),
                ('comments_per_hour', models.FloatField(default=140.35, null=True)),
                ('community_creation', models.IntegerField(default=1284042626000, null=True)),
                ('points', models.IntegerField(default=4449500, null=True)),
                ('posts_per_day', models.FloatField(default=87.36, null=True)),
                ('posts_per_hour', models.FloatField(default=3.64, null=True)),
                ('subscribers', models.IntegerField(default=4409293, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_module.token')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('likes', models.IntegerField(default=39654, null=True)),
                ('points', models.IntegerField(default=39654, null=True)),
                ('talking_about', models.IntegerField(default=26, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_module.token')),
            ],
        ),
        migrations.CreateModel(
            name='CodrepoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_total_issues', models.IntegerField(default=21327, null=True)),
                ('contributors', models.IntegerField(default=1003, null=True)),
                ('created_at', models.IntegerField(default=1292771803000, null=True)),
                ('forks', models.IntegerField(default=29844, null=True)),
                ('last_push', models.IntegerField(default=1631103202000, null=True)),
                ('last_update', models.IntegerField(default=1631100509000, null=True)),
                ('points', models.IntegerField(default=128093, null=True)),
                ('stars', models.IntegerField(default=56870, null=True)),
                ('subscribers', models.IntegerField(default=3845, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_module.token')),
            ],
        ),
    ]
