# Generated by Django 4.1.1 on 2023-12-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0006_twitterdata_techindicators_redditdata_facebookdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codrepodata',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codrepo_data', to='main_module.token'),
        ),
        migrations.AlterField(
            model_name='facebookdata',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_data', to='main_module.token'),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_data', to='main_module.token'),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='techindicators', to='main_module.token'),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_data', to='main_module.token'),
        ),
    ]
