# Generated by Django 4.1.1 on 2023-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0008_alter_codrepodata_closed_total_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codrepodata',
            name='closed_total_issues',
            field=models.IntegerField(default=21327, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='contributors',
            field=models.IntegerField(default=1003, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='created_at',
            field=models.IntegerField(default=1292771803000, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='forks',
            field=models.IntegerField(default=29844, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='last_push',
            field=models.IntegerField(default=1631103202000, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='last_update',
            field=models.IntegerField(default=1631100509000, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='points',
            field=models.IntegerField(default=128093, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='stars',
            field=models.IntegerField(default=56870, null=True),
        ),
        migrations.AlterField(
            model_name='codrepodata',
            name='subscribers',
            field=models.IntegerField(default=3845, null=True),
        ),
        migrations.AlterField(
            model_name='facebookdata',
            name='likes',
            field=models.IntegerField(default=39654, null=True),
        ),
        migrations.AlterField(
            model_name='facebookdata',
            name='points',
            field=models.IntegerField(default=39654, null=True),
        ),
        migrations.AlterField(
            model_name='facebookdata',
            name='talking_about',
            field=models.IntegerField(default=26, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='active_users',
            field=models.IntegerField(default=11157, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='comments_per_day',
            field=models.FloatField(default=3368.42, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='comments_per_hour',
            field=models.FloatField(default=140.35, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='community_creation',
            field=models.IntegerField(default=1284042626000, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='points',
            field=models.IntegerField(default=4449500, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='posts_per_day',
            field=models.FloatField(default=87.36, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='posts_per_hour',
            field=models.FloatField(default=3.64, null=True),
        ),
        migrations.AlterField(
            model_name='redditdata',
            name='subscribers',
            field=models.IntegerField(default=4409293, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='ema10',
            field=models.FloatField(default=21419.650556424, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='ema50',
            field=models.FloatField(default=23477.3946873044, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='ema_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bearish', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='macd_line',
            field=models.FloatField(default=-301.3443464701, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='macd_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bullish', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='macd_signal',
            field=models.FloatField(default=-864.379150169, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='mfi14',
            field=models.FloatField(default=76.7455530806, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='mfi14_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bullish', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='mom10',
            field=models.FloatField(default=1817.74, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='mom10_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bullish', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='rsi10',
            field=models.FloatField(default=69.1125657987, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='rsi10_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='neutral', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='rsi50',
            field=models.FloatField(default=43.2777984936, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='rsi50_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='neutral', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='sma10',
            field=models.FloatField(default=20957.507, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='sma50',
            field=models.FloatField(default=23114.7386, null=True),
        ),
        migrations.AlterField(
            model_name='techindicators',
            name='sma_sentiment',
            field=models.CharField(choices=[('bullish', 'bullish'), ('bearish', 'bearish'), ('neutral', 'neutral')], default='bearish', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='account_creation',
            field=models.IntegerField(default=1313643968000, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='favourites',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='followers',
            field=models.IntegerField(default=844049, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='following',
            field=models.IntegerField(default=165, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='lists',
            field=models.IntegerField(default=6631, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='points',
            field=models.IntegerField(default=91055, null=True),
        ),
        migrations.AlterField(
            model_name='twitterdata',
            name='statuses',
            field=models.IntegerField(default=2031, null=True),
        ),
    ]
